apiVersion: v1
kind: Service
metadata:
  name: hazelcast-management-center-loadbalancer
spec:
  type: LoadBalancer
  clusterIP: ""
  selector:
    app: hazelcast
    role: mancenter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
