apiVersion: v1
kind: Service
metadata:
  name: hazelcast-loadbalancer
spec:
  type: LoadBalancer
  clusterIP: ""
  selector:
    app: hazelcast
    role: hazelcast
  ports:
  - protocol: TCP
    port: 5701
